package school.sorokin.event_manager.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import school.sorokin.event_manager.model.Location;
import school.sorokin.event_manager.model.dto.LocationDto;
import school.sorokin.event_manager.model.entity.LocationEntity;
import school.sorokin.event_manager.repository.LocationRepository;

import java.util.List;
import java.util.NoSuchElementException;

@Service
public class LocationService {

    private static final Logger log = LoggerFactory.getLogger(LocationService.class);

    private final LocationRepository locationRepository;

    public LocationService(LocationRepository locationRepository) {
        this.locationRepository = locationRepository;
    }

    @Transactional
    public LocationDto createLocation(LocationDto locationDto) {
        if (locationDto.getId() != null) {
            throw new IllegalArgumentException("When creating an ID, it must be generated by the database.");
        }
        LocationEntity locationEntity = locationRepository.save(toEntity(locationDto));
        LocationDto result = toDto(locationEntity);
        log.info("Create success {}", result);
        return result;
    }

    @Transactional(readOnly = true)
    public List<LocationDto> getAllLocations() {
        List<LocationEntity> entities = locationRepository.findAll();
        return entities.stream().map(this::toDto).toList();
    }

    @Transactional(readOnly = true)
    public LocationDto getLocationById(Long id) {
        return toDto(loadById(id));
    }

    @Transactional
    public LocationDto updateLocation(LocationDto locationDto, Long id) {
        LocationEntity loaded = loadById(id);
        checkCapacityNotReduced(loaded, toBusinessEntity(locationDto));
        LocationEntity updated = updatedFields(loaded, locationDto);
        LocationDto result = toDto(locationRepository.save(updated));
        log.info("Update success {}", result);
        return result;
    }

    @Transactional
    public void deleteLocation(Long id) {
        LocationEntity locationEntity = loadById(id);
        locationRepository.delete(locationEntity);
        log.info("Delete success {}", locationEntity);
    }

    private LocationEntity loadById(Long id) {
        return locationRepository.findById(id).orElseThrow(() -> new NoSuchElementException(
                "Location with id = " + id + " no found."));
    }

    private void checkCapacityNotReduced(LocationEntity loaded, Location updated) {
        if (loaded.getCapacity() > updated.getCapacity()) {
            throw new IllegalArgumentException("You are trying to reduce the capacity at an event");
        }
    }

    private Location toBusinessEntity(LocationDto dto) {
        return new Location(
                dto.getId(),
                dto.getName(),
                dto.getAddress(),
                dto.getCapacity(),
                dto.getDescription()
        );
    }

    private LocationEntity updatedFields(LocationEntity locationExisting, LocationDto updated) {
        return new LocationEntity(
                locationExisting.getId(),
                updated.getName(),
                updated.getAddress(),
                updated.getCapacity(),
                updated.getDescription()
        );
    }

    private LocationEntity toEntity(LocationDto locationDto) {
        return new LocationEntity(
                locationDto.getId(),
                locationDto.getName(),
                locationDto.getAddress(),
                locationDto.getCapacity(),
                locationDto.getDescription()
        );
    }

    private LocationDto toDto(LocationEntity locationEntity) {
        return new LocationDto(
                locationEntity.getId(),
                locationEntity.getName(),
                locationEntity.getAddress(),
                locationEntity.getCapacity(),
                locationEntity.getDescription()
        );
    }
}

